name: SonarCloud

on:
  push:
    branches:
      - flutterflow
  pull_request:
    branches:
      - flutterflow

jobs:
  build:
    name: Analyze with SonarCloud
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.4'

      - name: Install dependencies
        run: flutter pub get

      - name: Run SonarCloud Analysis
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          organization: ghaida-alsalamah
          projectKey: ghaida-alsalamah_SWproject1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

