name: SonarCloud

on:
  push:
    branches:
      - flutterflow
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: SonarCloud
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.4'  # Adjust if your Flutter version is different

      - name: Install dependencies
        run: flutter pub get
      - name: Build Flutter Web
        run: flutter build web



      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: ghaida-alsalamah_SWproject1
          SONAR_ORGANIZATION: ghaida-alsalamah
