name: Flutter Test Coverage

on:
  push:
    branches:
      - flutterflow
  pull_request:
    branches:
      - flutterflow

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'  # or your project's version 00

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests with coverage
        run: |
          flutter test --coverage
          genhtml coverage/lcov.info -o coverage/html
        continue-on-error: true

      - name: Install lcov
        run: sudo apt-get install lcov

      - name: Upload coverage to Code Climate
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_REPO_TOKEN }}
        with:
          coverageLocations: coverage/lcov.info:lcov

      - name: Run tests with coverage
        run: flutter test --coverage
        
      - name: Generate LCOV report
        run: genhtml coverage/lcov.info --output-directory coverage/html
      - name: Publish coverage
        run: ./cc-reporter after-build --exit-code $?
          

