name: Flutter Test Coverage

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: |
          dart pub get
          
      - name: Print pubspec.yaml (for debugging)
        run: cat pubspec.yaml

      - name: Run tests with coverage
        run: |
          dart pub global activate coverage
          dart test --coverage=coverage
          dart pub global run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --report-on=lib

# Uncomment below after tests pass
#      - name: Upload coverage to Code Climate
#        uses: paambaati/codeclimate-action@v5.0.0
#        env:
#          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
#        with:
#          coverageLocations: coverage/lcov.info:lcov
